name: haoyun_peimei_hive_clone
description: 克隆“好云配煤”App v1.0.17 Flutter + Hive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
